[project]
name = "rover-embassy-docs"
version = "0.1.0"
description = "Rover Embassy Control System Documentation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["mkdocs-material>=9.6.14"]
